### ISSUE TITLE
Issue with Build Provider - Go Sum Mismatch

### ISSUE THREAD

**Issue by james-crowley** [terraform-providers/terraform-provider-cohesity#2]
## 🐛 Bug Report
When building `v1.0.0` or `master` the following error happens:

```
verifying github.com/cohesity/management-sdk-go@v1.1.2: checksum mismatch
	downloaded: h1:1hoBoKaEWam4aSaSkRzCr5zJkG0Ma7dTcLzEcBUQ43o=
	go.sum:     h1:y0YUqNP7qrno+hOk3fR0U1MLbEsBz71a22MZopghlxY=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
```

This looks like the `management-sdk-go` file has been modify/changed, thus when Go tries to pull down the package it results in a mismatch checksum.

## To Reproduce

1. git clone https://github.com/terraform-providers/terraform-provider-cohesity.git
2. git checkout v1.0.0
3. go build

## Expected behavior
I expect when building the provider, it would build without error and produce a binary.

## Actual Behavior
See error posted above.

@anvesh-cohesity @chandrashekar-cohesity Any fixes in mind?

**Comment by chandrashekar-cohesity** [comment]
Thanks for letting us know. We will check it out and get back soon.

**Comment by anvesh-cohesity** [comment]
@james-crowley Failed to reproduce the issue following the steps mentioned in 'To Reproduce'. Tried it on Mac and Centos 7 machines, the builds went through successfully without any issues. What is the os and golang version you were using?

**Comment by anvesh-cohesity** [comment]
Seems like an issue with golang version, can you please upgrade version >= go 1.12 and check. Also please check https://stackoverflow.com/questions/54133789/go-modules-checksum-mismatch
